### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by lfb0801**
added Question and Improvement Request templates

### CODE REVIEW

**Review by MindHawk — DISMISSED** [review]
No code changed. Updated templates seem fine to me.

**Review by larsvandriel — DISMISSED** [review]

**Comment by larsvandriel** [comment]
Seems like they are usefull templates.

**Review by chf3kl9 — APPROVED** [review]

**Review by MindHawk — APPROVED** [review]
Templates still fine according to me.

**Review by MichielLangen — APPROVED** [review]
***nice***

**Review by larsvandriel — APPROVED** [review]

**Review by Zeehond99 — APPROVED** [review]

**Review by lmtjanssen — APPROVED** [review]

**Pull request merged**
